### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by peterwilson3912** [Sreyan88/GAMA#15]
Hi! Thanks for the good project! I am running `finetune.py` for CompA-R dataset as i want to figure out training on my own dataset. I met this error for the line:

https://github.com/Sreyan88/GAMA/blob/main/finetune.py#L288

```
 trainer = transformers.Trainer(
        model=model,
        train_dataset=train_data,
        eval_dataset=val_data,
```

```
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
<class 'peft.tuners.lora.LoraModel'>
Downloading data files: 100%|████████████████| 1/1 [00:00<00:00, 9642.08it/s]
Extracting data files: 100%|█████████████████| 1/1 [00:00<00:00, 1376.99it/s]
Generating train split: 494 examples [00:00, 59323.34 examples/s]
trainable params: 0 || all params: 6991619072 || trainable%: 0.0
Map: 100%|████████████████████████| 494/494 [00:00<00:00, 1508.15 examples/s]
Traceback (most recent call last):
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/iscprox1/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/iscprox1/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/iscprox1/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/iscprox1/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/iscprox1/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/iscprox1/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/mnt/NVME-VM/projects/GAMA/finetune.py", line 348, in <module>
    fire.Fire(train)
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/NVME-VM/projects/GAMA/finetune.py", line 311, in train
    trainer = transformers.Trainer(
  File "/mnt/NVME-VM/projects/GAMA/hf-dev-train/transformers-main/src/transformers/trainer.py", line 478, in __init__
    self._move_model_to_device(model, args.device)
  File "/mnt/NVME-VM/projects/GAMA/hf-dev-train/transformers-main/src/transformers/trainer.py", line 720, in _move_model_to_device
    model = model.to(device)
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/mnt/NVME-VM/anaconda3/envs/gama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

i assume this is a data reading error. I even change the JSON file to the "audio_id" to be an absolute path to be like `"audio_id": "/mnt/NVME-VM/projects/GAMA/data/test/acl_sk_24/filtered_audios/Y0SSy52rc1BM.wav",`

May I ask do you know where the possible problem is? Thank you so much!!!

**Comment by Sreyan88** [comment]
Hi @kayleeliyx ,

Can you please try training the model on A6000. This similar error was mentioned in #3

**Comment by peterwilson3912** [comment]
This error usually happens when you're loading a model in a "meta" mode using device_map="auto". The meta tensors do not hold real data; they only serve as placeholders. ways of debugging:

```
    for name, param in model.named_parameters():
        print(f"{name} is on {param.device}")
```
so that you will know where the models are. you are expected to see like:
![image](https://github.com/user-attachments/assets/eced9d6b-fe0e-480e-b898-5dd577965636)
instead of "meta". having a bigger ram gpu will solve this.

**Comment by Sreyan88** [comment]
Great to know that the problem is solved!
