### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by peterwilson3912** [Sreyan88/GAMA#16]
```
/home/.conda/envs/gama/lib/python3.10/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 5, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/GAMA/train_script/../finetune.py", line 357, in <module>
    fire.Fire(train)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/GAMA/train_script/../finetune.py", line 352, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/trainer.py", line 1638, in train
    return inner_training_loop(
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/trainer.py", line 1661, in _inner_training_loop
    num_update_steps_per_epoch = len_dataloader // args.gradient_accumulation_steps
ZeroDivisionError: integer division or modulo by zero

```

I met this error while training using compa-r dataset. May i ask what is this `gradient_accumulation_steps`? Thank you so much!

**Comment by Sreyan88** [comment]
Hi @kayleeliyx , 

You can find the definition of `gradient_accumulation_steps` here: https://www.hopsworks.ai/dictionary/gradient-accumulation

effective_batch_size = batch_size * gradient_accumulation_steps

**Comment by kayleeliyx** [comment]
Thank you so much! May I ask if you have a suggestion as to why my `gradient_accumulation_steps` is zero and how to fix it? I am just training on the compa-r dataset. thank you so much!

**Comment by peterwilson3912** [comment]
Thanks for helping! The batch size value should be larger than 4. I got this error because I set the batch size as 2. Thanks!
