### ISSUE TITLE
ValueError: Unable to create tensor for timestamp_events

### ISSUE THREAD

**Issue by peterwilson3912** [Sreyan88/GAMA#17]
```
Traceback (most recent call last):
  File "/home/.conda/envs/gama/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/.conda/envs/gama/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/GAMA/finetune.py", line 350, in <module>
    fire.Fire(train)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/GAMA/finetune.py", line 345, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/trainer.py", line 1638, in train
    return inner_training_loop(
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/trainer.py", line 1875, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/tokenization_utils_base.py", line 717, in convert_to_tensors
    tensor = as_tensor(value)
ValueError: too many dimensions 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/data/data_collator.py", line 644, in __call__
    new_features = self.tokenizer.pad(
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/tokenization_utils_base.py", line 3034, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/tokenization_utils_base.py", line 210, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/tokenization_utils_base.py", line 733, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`timestamp_events` in this case) have excessive nesting (inputs type `list` where type `int` is expected)
```

I met several error with the format of the dataset as the instruction_output has three instruction and three output. However, it seems that the model can only take one instruction and one output, which may causing the error as mentioned in https://github.com/Sreyan88/GAMA/issues/14

However, while i train using compa-r dataset. i met the error saying keyword instructions here:

https://github.com/Sreyan88/GAMA/blob/main/hf-dev-train/transformers-main/src/transformers/data/data_collator.py#L632

```
        for key in ['instruction', 'input', 'dataset', 'task', 'output']: #tokenizer_input_bert
            for feature in new_features:
                if key == 'tokenizer_input_bert':
                    bert_features.append(feature[key])
                feature.pop(key)
 ```

I directly tried to change the dataset to be:
```
    {
      "audio_id": "Y0SSy52rc1BM.wav",
      "input": "",
      "dataset": "Audioset_Strong",
      "task": "open-ended question",
    "instruction": "Given the presence of choir and music, infer the possible occasion or event taking place. Use the auditory observations to corroborate with the possible visual cues.",
        "output": "The choir and music suggest a celebratory event, possibly a festive occasion or performance event, and the visual cues corroborate with a dance or party setting.",
      "timestamp_events": "['(Choir-0.0-1.932)', '(Music-0.0-10.0)', '(Hubbub, speech noise, speech babble-0.0-10.0)', '(Choir-3.092-10.0)']"
    },
```

where there is just one instruction and one output in json, it still doesn't work ( the error is shown above). 

it says 
```
  File "/nfs/turbo/coe-apsample/LLM_Acoustic/GAMA/hf-dev-train/transformers-main/src/transformers/tokenization_utils_base.py", line 717, in convert_to_tensors
    tensor = as_tensor(value)
ValueError: too many dimensions 'str'
```
```
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`timestamp_events` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```

which seems to be some formatting is wrong with timestamp_events?
It seems to be the case that the code and the dataset do not exactly match the format. Could you let me know where the problem could be? Thank you so much for your help!

**Comment by peterwilson3912** [comment]
I am also very curious: How did the author use the timestamp_events information? From the code, it seems that timestamp_events is just labelled in the dataset but not used in the whole pipeline. Thank you so much for your help!

**Comment by sonalkum** [comment]
@kayleeliyx You are correct, we don't use the timestamp_events in the pipeline. For your error, you can ignore the timestamps_events., and check if the issue still exists.
