### ISSUE TITLE
steps after finetune the model on my own dataset

### ISSUE THREAD

**Issue by peterwilson3912** [Sreyan88/GAMA#20]
Hi! I want to finetune the model with my own dataset. Therefore, I update the path of the downloaded Llama-2-7b-chat-hf-qformer in [finetune.py](https://github.com/Sreyan88/GAMA/blob/main/finetune.py) on lines 93 and 98.
like this:

```
base_model = './Llama-2-7b-chat-hf-qformer'
```
then i wrote the bash file like this:

```
#!/bin/bash


export TRANSFORMERS_CACHE=cache/
export HF_DATASETS_CACHE=cache/
export CUDA_VISIBLE_DEVICES=0

output_dir='../isomic_output/'
mkdir -p $output_dir
cp "$0" ${output_dir}/$(date +"%Y-%m-%d-%H-%M-%S").sh

torchrun --nproc_per_node=1 --master_port=1234 ../finetune.py \
    --base_model '../Llama-2-7b-chat-hf-qformer' \
    --data_path '../data/IsoMic/clean_steer_mono_gama_updated.json' \
    --output_dir $output_dir \
    --batch_size 128 \
    --micro_batch_size 4 \
    --num_epochs 2 \
    --learning_rate 1e-3 \
    --cutoff_len 108 \
    --val_set_size 0 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules ['dummy'] \
    --train_on_inputs \
    --wandb_run_name ${output_dir} \
    --group_by_length \
    --save_steps 500 \
    --trainable_params qformer
```

after running the finetune for 2 epoch, i got the final loss. the loss is decreasing during training. the final loss is 0.4. i got these output files:
<img width="233" alt="image" src="https://github.com/user-attachments/assets/d16deadc-098d-471d-88a1-da2fdb7607fd">

Then I update the line in the `gama_inf.py` [here](https://github.com/Sreyan88/GAMA/blob/main/gama_inf.py#L216) to load the `adapter_model.bin` and then run the `gama_inf.py` on my test dataset. But I got the error:

```
  0%|                                                                                                 | 0/3999 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/GAMA/gama_inf.py", line 301, in <module>
    fire.Fire(main)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/GAMA/gama_inf.py", line 276, in main
    generation_output = model.generate(
  File "/GAMA/peft-main/src/peft/peft_model.py", line 539, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/.conda/envs/gama/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/generation/utils.py", line 1472, in generate
    return self.sample(
  File "/GAMA/hf-dev-train/transformers-main/src/transformers/generation/utils.py", line 2541, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

May I ask if there is something wrong with my steps, or do you have any suggestions on where the problem could be? Thank you so much for your help and this is really a great project.

**Comment by sonalkum** [comment]
Hi @kayleeliyx , you should use `pytorch_model.bin` and not adapter.

**Comment by peterwilson3912** [comment]
For some reason, pytorch_model.bin is not generated. should I go through all five stages to train, or is there something wrong with my .sh file?

**Comment by sonalkum** [comment]
@kayleeliyx what is your dataset size? also reduce the --save_steps from 500 to 10 to check if pytorch_model.bin gets saved or not.
